In [1]:
import duckdb

ModuleNotFoundError: No module named 'duckdb'

In [6]:
import duckdb

In [2]:
import pandas as pd
import os
from datetime import datetime

In [7]:
con = duckdb.connect(database='dados-duckdb.db', read_only=False)

In [ ]:
df = pd.read_csv('../landing/z0019_1.csv', sep=';')

In [16]:
df.head()

   NATBB     MAKTX WERKS  MAINS  LABST
0  10001  PARAFUSO  BT10    100    100
1  10002   MARTELO  BT50    100   1500
2  10003     PREGO  BT10    100     50

In [17]:
arquivo='z0019_1.csv'
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df.head()

   NATBB     MAKTX WERKS  MAINS  LABST
0  10001  PARAFUSO  BT10    100    100
1  10002   MARTELO  BT50    100   1500
2  10003     PREGO  BT10    100     50

In [18]:
print(datetime.now())

2026-10-12 15:18:13.643491

In [4]:
arquivo = 'z0019_1.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}', sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBB     MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10    100    100  z0019_1.csv 2026-10-13 18:46:03.343011
1  10002   MARTELO  BT50    100   1500  z0019_1.csv 2026-10-13 18:46:03.343011
2  10003     PREGO  BT10    100     50  z0019_1.csv 2026-10-13 18:46:03.343011

In [11]:
import duckdb

con = duckdb.connect(database='dados-duckdb.db', read_only=False)

In [12]:
con.execute("""
CREATE TABLE IF NOT EXISTS bronze_produtos (
    NATBR VARCHAR,
    MAKTX VARCHAR,
    WERKS VARCHAR,
    MAINS VARCHAR,
    LABST VARCHAR,
    nome_arquivo VARCHAR,
    data_ingestao TIMESTAMP,
)
""")

In [19]:
resultado = con.execute("SELECT*FROM bronze_z0019").fetchdf()
print(resultado)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-10-12 15:20:41.295774
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-10-12 15:20:41.295774
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-10-12 15:20:41.295774
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-10-12 15:29:56.522429
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-10-12 15:29:56.522429
5  10003     PREGO  BT10   100    60  z0019_2.csv 2026-10-12 15:29:56.522429

In [20]:
resultado.head(6)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-10-12 15:20:41.295774
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-10-12 15:20:41.295774
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-10-12 15:20:41.295774
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-10-12 15:29:56.522429
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-10-12 15:29:56.522429
5  10003     PREGO  BT10   100    60  z0019_2.csv 2026-10-12 15:29:56.522429

In [16]:
con.execute("ALTER TABLE bronze_produtos RENAME TO bronze_z0019")

In [21]:
con.close()